name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
      # optional if kubectl isn't preinstalled
        uses: azure/setup-kubectl@v4

      - name: Lint/validate manifests (client-side)
        run: kubectl apply --dry-run=client --validate=false -f manifests/

      - name: Verify scripts
        run: make verify